name: Build WPF

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore APPQLXD.sln

      - name: Build
        run: dotnet build APPQLXD.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish APPQLXD/APPQLXD.csproj `
          --configuration Release `
          --runtime win-x64 `
          --self-contained true `
          --output publish

      - name: Create ZIP
        run: Compress-Archive -Path publish\* -DestinationPath APPQLXD-Windows.zip

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: APPQLXD-Windows
          path: APPQLXD-Windows.zip
